### ISSUE TITLE
No theming after changing baseurl

### ISSUE THREAD

**Issue by nxjosephofficial** [jitinnair1/gradfolio#23]
Hello. After changing `baseurl: /gradfolio #name of GitHub repository` to `baseurl: /`, theme is not appearing.

**Comment by jitinnair1** [comment]
Hi @nxjosephofficial, so if you want the site to be available at `username.github.io` then the `baseurl` and `url` need to be set as:

```yaml
baseurl: "\"
url: "https://username.github.io"
```

Also, the name of the repo should be "username.github.io". Let me know if this fixes the error

**Comment by nxjosephofficial** [comment]
I'm testing it in local so I don't specify an url. Stylings not working if `baseurl` is not set to `/gradfolio`.

**Comment by jitinnair1** [comment]
If in the local environment, you set `baseurl` to "/gradfolio" your local URL will be "http://127.0.0.1:4000/gradfolio/". You can check this when you run "bundle exec jekyll serve" or "jekyll serve" (screenshot attached)

Alternatively, you can set the `baseurl` to "/" to get the site deployed locally at "http://127.0.0.1:4000/"

![github](https://user-images.githubusercontent.com/2485715/199530861-49c1f3d1-6b78-4351-8c20-39fe31214950.png)

Please let me know if the problem persists.

**Comment by nxjosephofficial** [comment]
I recorded a video about the issue.

https://user-images.githubusercontent.com/61632416/199551496-936d6f9f-9920-4bae-8577-0cf94ec9f3a1.mp4

In the end, I kept `baseurl:` empty and it worked.
