### ISSUE TITLE
Mobile friendly navigation

### ISSUE THREAD

**Issue by aleksandar-trifunovic** [jitinnair1/gradfolio#3]
Hi Jitin,
I really like how gradfolio is built. 

It would be nice to have more mobile-friendly navigation. Current navigation is responsive, but it would be a nice feature to implement it using hamburger menu or similar feature like that.

**Comment by jitinnair1** [comment]
Hi Alex, 

Thanks for the suggestion, I can see what you mean. Instead of adding a hamburger though, I'll probably make the navbar scrollable horizontally.
